apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |

    server {
      listen 80;
      index index.html;
      root /usr/share/nginx/html;

      add_header Content-Type text/html;
      return 200 'Code.education Rocks';
    }